site_name: Learning Book
site_url: https://note.liuli.hots/
theme:
    name: mkdocs
    navigation_depth: 4
    sticky_navigation: False
    include_homepage_in_sidebar: False
    collapse_navigation: False
    titles_only: False
    locale: zh_CN
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - bash
        - shell
markdown_extensions:
    - toc:
        baselevel: 2
nav:
  - Home: 'index.md'
  - Shell:
      - 'Shell 概述': '01-Shell 概述.md'
      - '编辑器': '02-编辑器.md'
      - '脚本设计': '03-脚本设计.md'
      - 'Shell 变量': '04-Shell 变量.md'
      - '算数运算': '05-算数运算.md'
      - '流程控制': '06-流程控制.md'
      - '文本编辑': '07-文本编辑.md'
      - 'Shell 函数': '08-Shell 函数.md'
      - 'Shell 数组': '09-Shell 数组.md'
      - '字符和字符串': '10-字符和字符串.md'
      - '正则表达式': '11-正则表达式.md'
      - '输入与输出': '12-输入与输出.md'
      - 'Shell 高级应用': '13-Shell 高级应用.md'
  - Python:
      - '基础语法': 'base.md'
      - '面向对象': 'object.md'
      - '多任务编程': 'multi-process.md'
      - 'TCP 网络应用开发': 'tcp-socket.md'
      - 'Web 服务器开发': 'web-server.md'
      - 'Python 高级语法': 'advanced.md'
      - 'Django 框架': 'django.md'
      - 'Flask 框架': 'flask.md'
