site_name: Learning Book
site_url: https://note.liuli.hots/
theme:
    name: mkdocs
    navigation_depth: 4
    sticky_navigation: False
    include_homepage_in_sidebar: False
    collapse_navigation: True
    titles_only: False
    locale: zh_CN
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - bash
        - shell

markdown_extensions:
    - toc:
        baselevel: 2
nav:
    - Linux: 
        - '入门命令': 'Linux/1-1-Linux 基本命令.md'
        - '文件管理': 'Linux/1-2-Linux 文件管理.md'
        - '用户管理': 'Linux/1-3-Linux 用户管理.md'
        - '权限管理': 'Linux/1-4-Linux 权限管理.md'
        - '进程检测': 'Linux/1-5-Linux 进程检测.md'
        - '高级命令拓展': 'Linux/1-6-Linux 高级命令拓展.md'
        - 'YUM 仓库': 'Linux/1-7-Linux YUM 源仓库.md'
    - Shell:
        - '概述': 'Shell/01-Shell 概述.md'
        - '编辑器': 'Shell/02-编辑器.md'
        - '脚本设计': 'Shell/03-脚本设计.md'
        - '变量': 'Shell/04-Shell 变量.md'
        - '算数运算': 'Shell/05-算数运算.md'
        - '流程控制': 'Shell/06-流程控制.md'
        - '文本编辑': 'Shell/07-文本编辑.md'
        - '函数': 'Shell/08-Shell 函数.md'
        - '数组': 'Shell/09-Shell 数组.md'
        - '字符和字符串': 'Shell/10-字符和字符串.md'
        - '正则表达式': 'Shell/11-正则表达式.md'
        - '输入与输出': 'Shell/12-输入与输出.md'
        - '高级应用': 'Shell/13-Shell 高级应用.md'
    - Go:
        - '开发环境安装': 'Go/01-Go 开发环境安装配置.md'
        - '语法基础': 'Go/02-Go 语法基础.md'
        - '分支循环': 'Go/03-Go 分支循环.md'