site_name: Learning Book
site_url: https://note.liuli.hots/
theme:
    name: mkdocs
    navigation_depth: 4
    sticky_navigation: False
    include_homepage_in_sidebar: False
    collapse_navigation: True
    titles_only: False
    locale: zh_CN
    highlightjs: true
    hljs_languages:
        - yaml
        - python
        - bash
        - shell

markdown_extensions:
    - toc:
        baselevel: 2
nav:
    - Linux 基础: 
        - '入门命令': 'Linux/1-1-Linux 基本命令.md'
        - '文件管理': 'Linux/1-2-Linux 文件管理.md'
        - '用户管理': 'Linux/1-3-Linux 用户管理.md'
        - '权限管理': 'Linux/1-4-Linux 权限管理.md'
        - '进程检测': 'Linux/1-5-Linux 进程检测.md'
        - '高级命令拓展': 'Linux/1-6-Linux 高级命令拓展.md'
    - 系统服务:
        - 'YUM 软件仓库': 'Linux/1-7-Linux YUM 源仓库.md'
        - 'NTP 时间同步服务': 'Linux/2-1-NTP 服务.md'
        - 'SSH 远程登录服务': 'Linux/2-2-SSH 服务.md'
        - 'RSYNC 文件同步服务': 'Linux/2-3-RSYNC 服务.md'
        - 'FTP 文件共享服务': 'Linux/2-4-FTP 服务.md'
        - 'NFS 文件共享服务': 'Linux/2-5-NFS 服务.md'
        - 'SAMBA 文件共享服务': 'Linux/2-6-SAMBA 服务.md'
        - 'DNS 域名解析服务': 'Linux/2-7-DNS 服务.md'
    - Shell 编程:
        - '概述': 'Shell/01-Shell 概述.md'
        - '编辑器': 'Shell/02-编辑器.md'
        - '脚本设计': 'Shell/03-脚本设计.md'
        - '变量': 'Shell/04-Shell 变量.md'
        - '算数运算': 'Shell/05-算数运算.md'
        - '流程控制': 'Shell/06-流程控制.md'
        - '文本编辑': 'Shell/07-文本编辑.md'
        - '函数': 'Shell/08-Shell 函数.md'
        - '数组': 'Shell/09-Shell 数组.md'
        - '字符和字符串': 'Shell/10-字符和字符串.md'
        - '正则表达式': 'Shell/11-正则表达式.md'
        - '输入与输出': 'Shell/12-输入与输出.md'
        - '高级应用': 'Shell/13-Shell 高级应用.md'
    - Python 编程:
        - 'Python 基础': 'Python/index.html'
        - 'Django 基础使用': 'Python/Django01/04_Web框架之Django一.md'
        - 'Django 类视图与模板': 'Python/Django02/05_Web框架之Django二.md'
        - 'Django ORM使用': 'Python/Django03/06_Web框架之Django三.md'
    - Web 编程:
        - 'HTML\CSS': 'Web/HTML-CSS/01_Web开发基础之HTML+CSS.md'
        - 'JavaScript': 'Web/JavaScript/02_Web开发基础之JavaScript.md'
        - 'jQuery\Bootstrap\Ajax': 'Web/jQuery-Bootstrap-Ajax/03_Web开发基础之综合应用.md'
    - Go 编程:
        - '开发环境安装': 'Go/01-Go 开发环境安装配置.md'
        - '语法基础': 'Go/02-Go 语法基础.md'
        - '数据类型': 'Go/03-Go 数据类型.md'
        - '分支循环': 'Go/04-Go 分支循环.md'
        - '指针': 'Go/05-Go 指针.md'
        - '函数': 'Go/06-Go 函数.md'
        - '线性表': 'Go/07-线性表.md'
        - '数组与切片': 'Go/08-Go 数组、切片.md'
        - '编码与字符串': 'Go/09-字符串编码.md'
        - '哈希表': 'Go/10-哈希表.md'
        - 'Map': 'Go/11-Go Map.md'
        - '排序': 'Go/12-Go 排序.md'
        - '结构体': 'Go/13-Go 结构体.md'
        - '接口与面向对象': 'Go/14-Go 接口与面向对象.md'
        - '错误处理': 'Go/15-Go 错误处理.md'
        - '序列化与反序列化': Go/16-序列化与反序列化.md'
        - '时间格式化': 'Go/17-时间.md'
        - '包管理': 'Go/18-包管理.md'
        - '日志输出': 'Go/19-日志输出.md'
        - '进程与线程': 'Go/20-进程与线程.md'
        - 'TCP编程': 'Go/21-TCP编程基础.md'
        - 'Goroutine协程': 'Go/22-Goroutine协程.md'
        - 'Channel通道': 'Go/23-Channel通道.md'
