apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress-mysql
    namespace: wordpress-space
    labels:
        app: wordpress
        tier: mysql
spec:
    selector:
        matchLabels:
            app: wordpress
            tier: mysql-pod
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: wordpress
                tier: mysql-pod
        spec:
            containers:
              - image: mysql:5.7
                name: mysql
                env:
                  - name: MYSQL_ROOT_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: mysql-pass
                            key: password
                  - name: MYSQL_DATABASE
                    valueFrom:
                        configMapKeyRef:
                            name: mysql-config
                            key: db-name
                ports:
                  - containerPort: 3306
                    name: mysql
                volumeMounts:
                  - name: mysql-persistent-storage
                    mountPath: /var/lib/mysql
            volumes:
              - name: mysql-persistent-storage
                persistentVolumeClaim:
                    claimName: mysql-pv-claim
