apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pv-claim
    namespace: wordpress-space
spec:
    storageClassName: stateful-nfs
    accessModes: ["ReadWriteOnce"]
    resources:
        requests:
            storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wordpress-pv-claim
    namespace: wordpress-space
spec:
    storageClassName: stateful-nfs
    accessModes: ["ReadWriteOnce","ReadWriteMany"]
    resources:
        requests:
            storage: 1Gi
