apiVersion: v1
kind: Service
metadata:
    name: mysql
    namespace: wordpress-space
    labels:
        app: mysql
spec:
    ports:
      - port: 3306
        targetPort: 3306
        protocol: TCP
    selector:
        app: wordpress
        tier: mysql-pod
    type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
    name: wordpress
    namespace: wordpress-space
    labels:
        app: wordpress
spec:
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
    selector:
        app: wordpress
        tier: frontend-pod
    type: ClusterIP
