apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pv1-claim
spec:
    storageClassName: stateful-nfs
    accessModes: ["ReadWriteOnce"]
    resources:
        requests:
            storage: 2Gi
